FUNCTION Z_GET_BOOKS.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(DATE1) TYPE  S_BDATE
*"     REFERENCE(DATE2) TYPE  S_BDATE
*"  EXPORTING
*"     REFERENCE(GTBOOKS) TYPE  ZTBOOKS
*"     REFERENCE(S_COUNT) TYPE  I
*"     REFERENCE(WEEKDAYS) TYPE  ZWEEKDAYS
*"  EXCEPTIONS
*"      NOT_FOUNT
*"----------------------------------------------------------------------

DATA: LS_DAY TYPE SBOOK,
      LV_DAY TYPE SCAL-INDICATOR.

select * from SBOOK into TABLE GTBOOKS
  where ORDER_DATE BETWEEN DATE1 and DATE2.

  IF sy-SUBRC is not INITIAL.
RAISE NOT_FOUNT.
  ENDIF.

DESCRIBE TABLE GTBOOKS LINES S_COUNT.

LOOP AT GTBOOKS INTO LS_DAY.

  CALL FUNCTION 'DATE_COMPUTE_DAY'
    EXPORTING
      DATE          = LS_DAY-ORDER_DATE
   IMPORTING
     DAY           = LV_DAY.
            .

CASE LV_DAY.
  WHEN '1'.
    ADD 1 TO WEEKDAYS-ZMONDAY.
  WHEN '2'.
    ADD 1 TO WEEKDAYS-ZTUESDAY.
  WHEN '3'.
    ADD 1 TO WEEKDAYS-ZWEDNESDAY.
  WHEN '4'.
    ADD 1 TO WEEKDAYS-ZTHURSDAY.
  WHEN '5'.
    ADD 1 TO WEEKDAYS-ZFRIDAY.
  WHEN '6'.
    ADD 1 TO WEEKDAYS-ZSATURDAY.
  WHEN '7'.
    ADD 1 TO WEEKDAYS-ZSUNDAY.
ENDCASE.


ENDLOOP.

ENDFUNCTION.
