*&---------------------------------------------------------------------*
*& Include          ZUDEMY31_TYPES
*&---------------------------------------------------------------------*

PARAMETERS: P_TARIH1 TYPE SBOOK-FLDATE,
            P_TARIH2 TYPE SBOOK-FLDATE.
WRITE 'dENEME'.

DATA: BEGIN OF TS_SBOOK,
        CARRID TYPE SBOOK-CARRID,
        CONNID TYPE SBOOK-CONNID,
        FLDATE TYPE SBOOK-FLDATE,
      END OF TS_SBOOK.

DATA: BEGIN OF TS_SPFLI,
        CARRID    TYPE SPFLI-CARRID,
        CONNID    TYPE SPFLI-CONNID,
        COUNTRYFR TYPE SPFLI-COUNTRYFR,
        CITYFROM  TYPE SPFLI-CITYFROM,
        COUNTRYTO TYPE SPFLI-COUNTRYTO,
        CITYTO    TYPE SPFLI-CITYTO,
        FLTIME    TYPE SPFLI-FLTIME,
        DEPTIME   TYPE SPFLI-DEPTIME,
      END OF TS_SPFLI.

DATA: BEGIN OF TS_SCARR,
        CARRID   TYPE SCARR-CARRID,
        CARRNAME TYPE SCARR-CARRNAME,
      END OF TS_SCARR.

DATA: BEGIN OF TS_FINAL,
        CARRID    TYPE SPFLI-CARRID,
        CARRNAME  TYPE SCARR-CARRNAME,
        CONNID    TYPE SPFLI-CONNID,
        COUNTRYFR TYPE SPFLI-COUNTRYFR,
        CITYFROM  TYPE SPFLI-CITYFROM,
        COUNTRYTO TYPE SPFLI-COUNTRYTO,
        CITYTO    TYPE SPFLI-CITYTO,
        FLDATE    TYPE SBOOK-FLDATE,
        FLTIME    TYPE SPFLI-FLTIME,
        DEPTIME   TYPE SPFLI-DEPTIME,
      END OF TS_FINAL.

DATA: GT_SBOOK LIKE TABLE OF TS_SBOOK,
      GT_SPFLI LIKE TABLE OF TS_SPFLI,
      GT_SCARR LIKE TABLE OF TS_SCARR,
      GT_DATA  LIKE TABLE OF TS_FINAL.
