*&---------------------------------------------------------------------*
*& Report ZALV_LIST
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZUDEMY334.
 TABLES: SBOOK, SCARR.

SELECTION-SCREEN BEGIN OF BLOCK EKRAN WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: s_date for SBOOK-ORDER_DATE OBLIGATORY NO INTERVALS NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK EKRAN.


SELECTION-SCREEN BEGIN OF BLOCK EKRAN2 WITH FRAME TITLE TEXT-002.
SELECT-OPTIONS: s_carid for SCARR-CARRID OBLIGATORY NO INTERVALS NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK EKRAN2.



DATA: GT_DATA TYPE ZTBOOK,
      GS_DATA TYPE ZSBOOK.


SELECT * FROM SBOOK AS SB
  JOIN SCARR AS SR ON SB~CARRID EQ SR~CARRID
  JOIN SPFLI AS SF ON SB~CONNID EQ SF~CONNID AND SB~CARRID EQ SF~CARRID
  INTO CORRESPONDING FIELDS OF TABLE GT_DATA
  WHERE SB~ORDER_DATE IN S_DATE.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
 EXPORTING
   I_STRUCTURE_NAME                  = 'ZSBOOK'
  TABLES
    T_OUTTAB                          = GT_DATA
          .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.
