*&---------------------------------------------------------------------*
*& Report ZUDEMY20
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZUDEMY23.

TABLES: SCARR, SBOOK.

DATA: BEGIN OF TS_SBOOK,
        CARRID TYPE SBOOK-CARRID,
        CONNID TYPE SBOOK-CONNID,
        FLDATE TYPE SBOOK-FLDATE,
        BOOKID TYPE SBOOK-BOOKID,
      END OF TS_SBOOK.

DATA: GT_SBOOK LIKE TABLE OF TS_SBOOK.
DATA: GT_SCARR LIKE TABLE OF SCARR,
      GS_SCARR LIKE LINE OF GT_SCARR.

data: gv_sayi TYPE i.
data: gv_mes TYPE c LENGTH 30.
data: gv_ctemp TYPE c LENGTH 3.

PARAMETERS: P_TARIH1 LIKE SBOOK-FLDATE,
p_tarih2 like SBOOK-FLDATE.

SELECT CARRID CONNID FLDATE BOOKID FROM SBOOK
  INTO TABLE GT_SBOOK
  WHERE FLDATE BETWEEN P_TARIH1 AND P_TARIH2.

IF SY-SUBRC IS NOT INITIAL.
  MESSAGE 'Kayıt bulunamadı' TYPE 'S' DISPLAY LIKE 'E'.
  CHECK 1 = 2.
ENDIF.

IF GT_SBOOK is INITIAL.
MESSAGE 'Kayıt bulunamadı' TYPE 'S' DISPLAY LIKE 'E'.
  CHECK 1 = 2.
ENDIF.

SELECT * FROM SCARR INTO TABLE GT_SCARR
  FOR ALL ENTRIES IN GT_SBOOK
  WHERE CARRID = GT_SBOOK-CARRID.

DESCRIBE TABLE GT_SCARR LINES GV_SAYI.
  move GV_SAYI to GV_CTEMP.
CONCATENATE 'Dönen kayıt Sayısı:' GV_CTEMP INTO GV_MES SEPARATED BY space.
MESSAGE GV_MES TYPE 'S'.

IF SY-SUBRC IS NOT INITIAL.
  MESSAGE 'Kayıt bulunamadı' TYPE 'S' DISPLAY LIKE 'E'.
  CHECK 1 = 2.
ENDIF.

LOOP AT GT_SCARR into GS_SCARR.
WRITE: GS_SCARR-CARRNAME, GS_SCARR-URL.
ENDLOOP.
