*&---------------------------------------------------------------------*
*& Report ZUDEMY27
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZUDEMY27.

PARAMETERS: P_TARIH1 TYPE SBOOK-FLDATE,
            P_TARIH2 TYPE SBOOK-FLDATE.

DATA: BEGIN OF TS_SBOOK,
        CARRID TYPE SBOOK-CARRID,
        CONNID TYPE SBOOK-CONNID,
        FLDATE TYPE SBOOK-FLDATE,
      END OF TS_SBOOK.

DATA: BEGIN OF TS_SPFLI,
        CARRID    TYPE SPFLI-CARRID,
        CONNID    TYPE SPFLI-CONNID,
        COUNTRYFR TYPE SPFLI-COUNTRYFR,
        CITYFROM  TYPE SPFLI-CITYFROM,
        COUNTRYTO TYPE SPFLI-COUNTRYTO,
        CITYTO    TYPE SPFLI-CITYTO,
        FLTIME    TYPE SPFLI-FLTIME,
        DEPTIME   TYPE SPFLI-DEPTIME,
      END OF TS_SPFLI.

DATA: BEGIN OF TS_SCARR,
        CARRID   TYPE SCARR-CARRID,
        CARRNAME TYPE SCARR-CARRNAME,
      END OF TS_SCARR.

DATA: BEGIN OF TS_FINAL,
        CARRID    TYPE SPFLI-CARRID,
        CARRNAME  TYPE SCARR-CARRNAME,
        CONNID    TYPE SPFLI-CONNID,
        COUNTRYFR TYPE SPFLI-COUNTRYFR,
        CITYFROM  TYPE SPFLI-CITYFROM,
        COUNTRYTO TYPE SPFLI-COUNTRYTO,
        CITYTO    TYPE SPFLI-CITYTO,
        FLDATE    TYPE SBOOK-FLDATE,
        FLTIME    TYPE SPFLI-FLTIME,
        DEPTIME   TYPE SPFLI-DEPTIME,
      END OF TS_FINAL.

DATA: GT_SBOOK LIKE TABLE OF TS_SBOOK,
      GT_SPFLI LIKE TABLE OF TS_SPFLI,
      GT_SCARR LIKE TABLE OF TS_SCARR,
      GT_DATA  LIKE TABLE OF TS_FINAL.

SELECT * FROM SBOOK
  INTO CORRESPONDING FIELDS OF TABLE GT_SBOOK
  WHERE FLDATE BETWEEN P_TARIH1 AND P_TARIH2.

IF GT_SBOOK IS INITIAL.
  MESSAGE 'Kayıt bulunamadı' TYPE 'S' DISPLAY LIKE 'E'.
  CHECK 1 = 2.
ENDIF.

SELECT * FROM SPFLI
  INTO CORRESPONDING FIELDS OF TABLE GT_SPFLI
  FOR ALL ENTRIES IN GT_SBOOK
  WHERE CARRID = GT_SBOOK-CARRID AND CONNID = GT_SBOOK-CONNID.

IF GT_SPFLI IS INITIAL.
  MESSAGE 'Kayıt bulunamadı' TYPE 'S' DISPLAY LIKE 'E'.
  CHECK 1 = 2.
ENDIF.

SELECT * FROM SCARR
  INTO CORRESPONDING FIELDS OF TABLE GT_SCARR
  FOR ALL ENTRIES IN GT_SPFLI
  WHERE CARRID = GT_SPFLI-CARRID.

IF GT_SCARR IS INITIAL.
  MESSAGE 'Kayıt bulunamadı' TYPE 'S' DISPLAY LIKE 'E'.
  CHECK 1 = 2.
ENDIF.

LOOP AT GT_SPFLI INTO TS_SPFLI.
  CLEAR TS_FINAL.

  MOVE-CORRESPONDING TS_SPFLI TO TS_FINAL.

  READ TABLE GT_SBOOK INTO TS_SBOOK
  WITH KEY CARRID = TS_SPFLI-CARRID CONNID = TS_SPFLI-CONNID.
  IF SY-SUBRC EQ 0.
    TS_FINAL-FLDATE = TS_SBOOK-FLDATE.
  ENDIF.

  READ TABLE GT_SCARR INTO TS_SCARR
  WITH KEY CARRID = TS_SPFLI-CARRID.
  IF SY-SUBRC EQ 0.
    TS_FINAL-CARRNAME = TS_SCARR-CARRNAME.
  ENDIF.

  APPEND TS_FINAL TO GT_DATA.

ENDLOOP.

CLEAR TS_FINAL.


LOOP AT GT_DATA into TS_FINAL.
write:/
 ts_final-CARRID
, ts_final-CARRNAME
, ts_final-CONNID
, ts_final-COUNTRYFR
, ts_final-CITYFROM
, ts_final-COUNTRYTO
, ts_final-CITYTO
, ts_final-FLDATE
, ts_final-FLTIME
, ts_final-DEPTIME.
ENDLOOP.
