*&---------------------------------------------------------------------*
*& Report ZUDEMY37
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZUDEMY37.
TABLES: ZTOGRENCILER, ZFAKULTELER, ZBOLUMLER.
TYPE-POOLS: SLIS.

DATA: BEGIN OF GT_ZTOGRENCILER OCCURS 0,
        SEL,
        FCODE     LIKE ZTOGRENCILER-FCODE,
        BCODE     LIKE ZTOGRENCILER-BCODE,
        OGRNUMBER LIKE ZTOGRENCILER-OGRNUMBER,
        AD        LIKE ZTOGRENCILER-AD,
        SOYAD     LIKE ZTOGRENCILER-SOYAD,
        DTARIH    LIKE ZTOGRENCILER-DTARIH,
        KTARIH    LIKE ZTOGRENCILER-KTARIH,
        FAD       LIKE ZFAKULTELER-AD,
        BAD       LIKE ZBOLUMLER-AD,
      END OF GT_ZTOGRENCILER.
data: gs_ogrenci like LINE OF GT_ZTOGRENCILER.
DATA: LAYOUT TYPE SLIS_LAYOUT_ALV.
DATA: FLCAT TYPE  SLIS_T_FIELDCAT_ALV.
data: flcat_row TYPE LINE OF SLIS_T_FIELDCAT_ALV.
DATA: VARIANT TYPE DISVARIANT.
VARIANT-REPORT = SY-REPID.
VARIANT-USERNAME = SY-UNAME.
LAYOUT-BOX_FIELDNAME = 'SEL'.

SELECTION-SCREEN BEGIN OF BLOCK SECIM WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS:
S_FKLT FOR ZTOGRENCILER-FCODE,
S_BLM FOR ZTOGRENCILER-BCODE,
S_OGRNO FOR ZTOGRENCILER-OGRNUMBER,
S_KAYIT FOR ZTOGRENCILER-KTARIH.
SELECTION-SCREEN END OF BLOCK SECIM.

SELECT
        ZO~FCODE
        ZO~BCODE
        ZO~OGRNUMBER
        ZO~AD
        ZO~SOYAD
        ZO~DTARIH
        ZO~KTARIH
        ZF~AD AS FAD
        ZB~AD AS BAD
  FROM ZTOGRENCILER AS ZO
  JOIN ZFAKULTELER AS ZF ON ZO~FCODE = ZF~CODE
  JOIN ZBOLUMLER AS ZB ON ZO~BCODE = ZB~CODE
  INTO CORRESPONDING FIELDS OF TABLE GT_ZTOGRENCILER
  WHERE ZO~FCODE IN S_FKLT
  AND ZO~BCODE IN S_BLM
  AND ZO~OGRNUMBER IN S_OGRNO
  AND ZO~KTARIH IN S_KAYIT.

CALL FUNCTION 'REUSE_ALV_FIELDCATALOG_MERGE'
  EXPORTING
    I_PROGRAM_NAME     = SY-REPID
    I_INTERNAL_TABNAME = 'GT_ZTOGRENCILER'
*   I_STRUCTURE_NAME   =
*   I_CLIENT_NEVER_DISPLAY       = 'X'
    I_INCLNAME         = SY-REPID
*   I_BYPASSING_BUFFER =
*   I_BUFFER_ACTIVE    =
  CHANGING
    CT_FIELDCAT        = FLCAT[]
*   EXCEPTIONS
*   INCONSISTENT_INTERFACE       = 1
*   PROGRAM_ERROR      = 2
*   OTHERS             = 3
  .

LOOP AT FLCAT INTO FLCAT_ROW.
CASE FLCAT_ROW-FIELDNAME.
  WHEN 'SEL'.
    FLCAT_ROW-TECH = 'X'.
  WHEN 'KTARIH'.
    FLCAT_ROW-EDIT = 'X'.
  WHEN OTHERS.
ENDCASE.

MODIFY FLCAT FROM FLCAT_ROW.

ENDLOOP.


CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
*   I_INTERFACE_CHECK        = ' '
*   I_BYPASSING_BUFFER       = ' '
*   I_BUFFER_ACTIVE          = ' '
    I_CALLBACK_PROGRAM       = SY-REPID
    I_CALLBACK_PF_STATUS_SET = 'SET_PF_STATUS'
   I_CALLBACK_USER_COMMAND  = 'USER_COMMAND'
*   I_CALLBACK_TOP_OF_PAGE   = ' '
*   I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*   I_CALLBACK_HTML_END_OF_LIST       = ' '
*   I_STRUCTURE_NAME         =
*   I_BACKGROUND_ID          = ' '
*   I_GRID_TITLE             =
*   I_GRID_SETTINGS          =
    IS_LAYOUT                = LAYOUT
    IT_FIELDCAT              = FLCAT[]
*   IT_EXCLUDING             =
*   IT_SPECIAL_GROUPS        =
*   IT_SORT                  =
*   IT_FILTER                =
*   IS_SEL_HIDE              =
*   I_DEFAULT                = 'X'
    I_SAVE                   = 'A'
    IS_VARIANT               = VARIANT
*   IT_EVENTS                =
*   IT_EVENT_EXIT            =
*   IS_PRINT                 =
*   IS_REPREP_ID             =
*   I_SCREEN_START_COLUMN    = 0
*   I_SCREEN_START_LINE      = 0
*   I_SCREEN_END_COLUMN      = 0
*   I_SCREEN_END_LINE        = 0
*   I_HTML_HEIGHT_TOP        = 0
*   I_HTML_HEIGHT_END        = 0
*   IT_ALV_GRAPHICS          =
*   IT_HYPERLINK             =
*   IT_ADD_FIELDCAT          =
*   IT_EXCEPT_QINFO          =
*   IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*   E_EXIT_CAUSED_BY_CALLER  =
*   ES_EXIT_CAUSED_BY_USER   =
  TABLES
    T_OUTTAB                 = GT_ZTOGRENCILER
* EXCEPTIONS
*   PROGRAM_ERROR            = 1
*   OTHERS                   = 2
  .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.


FORM SET_PF_STATUS USING RT_EXTAB TYPE SLIS_T_EXTAB.
  SET PF-STATUS 'MYGUI'.
  SET TITLEBAR 'MyTITLE'.
ENDFORM.

FORM USER_COMMAND USING R_UCOMM LIKE SY-UCOMM
      RS_SELFIELD TYPE SLIS_SELFIELD.

  RS_SELFIELD-REFRESH = 'X'.
  RS_SELFIELD-COL_STABLE = 'X'.
  RS_SELFIELD-ROW_STABLE = 'X'.

 DATA: REF_GRID TYPE REF  TO CL_GUI_ALV_GRID.

  IF REF_GRID IS INITIAL.
CALL FUNCTION 'GET_GLOBALS_FROM_SLVC_FULLSCR'
 IMPORTING
   E_GRID                           = REF_GRID.
  ENDIF.

  IF NOT REF_GRID IS INITIAL.
CALL METHOD REF_GRID->CHECK_CHANGED_DATA.
  ENDIF.
read TABLE GT_ZTOGRENCILER INTO GS_OGRENCI with KEY SEL = 'X'.
 CASE R_UCOMM.
 	WHEN 'DELETE'.
    delete FROM ZTOGRENCILER where OGRNUMBER = gs_ogrenci-OGRNUMBER.
  WHEN 'UPDATE'.
    UPDATE ZTOGRENCILER SET KTARIH = GS_OGRENCI-KTARIH
    WHERE OGRNUMBER = GS_OGRENCI-OGRNUMBER.
 ENDCASE.

ENDFORM.
