*&---------------------------------------------------------------------*
*& Report ZUDEMY13
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZUDEMY16.

DATA: GS_DATA  TYPE ZOGRENCI,
      GT_DATAS TYPE  ZOGRENCILER. "TABLE OF ZOGRENCI

DATA: GV_SAYI TYPE I.


"$. Region Tablo Doldurma

CLEAR GS_DATA.
GS_DATA-AD = 'Sait'.
GS_DATA-SOYAD = 'ORHAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'Aytül'.
GS_DATA-SOYAD = 'Korkut Şentürk'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'EMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'Bilal'.
GS_DATA-SOYAD = 'Orhan'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BPRO'.
APPEND GS_DATA TO GT_DATAS.


CLEAR GS_DATA.
GS_DATA-AD = 'KASIM'.
GS_DATA-SOYAD = 'BİLGİ'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'YMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'UMUTCAN'.
GS_DATA-SOYAD = 'SANHAL'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TIP'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'EYÜP'.
GS_DATA-SOYAD = 'GÖKHAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'MAKBULE'.
GS_DATA-SOYAD = 'YENİDÜNYA'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BPRO'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'AYLİA'.
GS_DATA-SOYAD = 'OKKAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'HUKUK'.
GS_DATA-SOYAD = 'ARMAĞAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'HEMS'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'HACI'.
GS_DATA-SOYAD = 'HASAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TIP'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'FETHİYE'.
GS_DATA-SOYAD = 'EKİNCİKLİ'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'IMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'MÜMTAZ'.
GS_DATA-SOYAD = 'TOY'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'İLKER'.
GS_DATA-SOYAD = 'ZENGİN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'MOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'HASİBE'.
GS_DATA-SOYAD = 'SÖZEN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'EMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'FÜSUN'.
GS_DATA-SOYAD = 'ÖZSOY'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'IMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ALTAN'.
GS_DATA-SOYAD = 'YAZICI'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'YMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'İSA'.
GS_DATA-SOYAD = 'SEVİMKAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'MMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'GÜLNAME'.
GS_DATA-SOYAD = 'SİMSER'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BPRO'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'DİNÇER'.
GS_DATA-SOYAD = 'AYDIN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BPRO'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ÖMER'.
GS_DATA-SOYAD = 'GÖKHAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'MMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ÜNSAL'.
GS_DATA-SOYAD = 'DERHEM'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'İSMAİL'.
GS_DATA-SOYAD = 'MİKDAT'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'HULUSİ'.
GS_DATA-SOYAD = 'KORU'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'YMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'EMRAH'.
GS_DATA-SOYAD = 'KEMAL'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'EMCED'.
GS_DATA-SOYAD = 'ARİFOĞLU'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TIP'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'MAHMUT'.
GS_DATA-SOYAD = 'ARDA'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TIP'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ÖZKAN'.
GS_DATA-SOYAD = 'USUL'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'SÜHEYLA'.
GS_DATA-SOYAD = 'AYÇA'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'BMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'FARİS'.
GS_DATA-SOYAD = 'COŞAR'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'IMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'MEHMET'.
GS_DATA-SOYAD = 'VEHBİ'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'EMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ASLIHAN'.
GS_DATA-SOYAD = 'ESRA'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'LÜTFÜ'.
GS_DATA-SOYAD = 'KURTEL'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'MOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'GÜLNUR'.
GS_DATA-SOYAD = 'KAVUTÇU'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'HEMS'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'GÜLSEREN'.
GS_DATA-SOYAD = 'BACAKSIZLAR'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'YMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'YAKUP'.
GS_DATA-SOYAD = 'ÖZÇELİK'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'YMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ABDULGAFUR'.
GS_DATA-SOYAD = 'KOL'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ÜMMÜ'.
GS_DATA-SOYAD = 'GÜLSÜM'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'IMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'SELÇUK'.
GS_DATA-SOYAD = 'DİNCER'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BPRO'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'YASER'.
GS_DATA-SOYAD = 'AKTOZ'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BPRO'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'GÜLHANIM'.
GS_DATA-SOYAD = 'ALİAĞAOĞLU'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'ISLT'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'BATURAY'.
GS_DATA-SOYAD = 'KANSU'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'BERRİN'.
GS_DATA-SOYAD = 'KÜTÜKDE'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'DUHAN'.
GS_DATA-SOYAD = 'ÖZ'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'ŞİFA'.
GS_DATA-SOYAD = 'İĞDE'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'YMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'TURGAY'.
GS_DATA-SOYAD = 'SİL'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TIP'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'GÖKNUR'.
GS_DATA-SOYAD = 'KÖKSAL'.
GS_DATA-CINSIYET = 'K'.
GS_DATA-BOLUM = 'BMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'BARAN'.
GS_DATA-SOYAD = 'AKDUMAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'HİSAR'.
GS_DATA-SOYAD = 'CAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'BENAN'.
GS_DATA-SOYAD = 'GENÇ'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'MMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'CUMHUR'.
GS_DATA-SOYAD = 'BAYTAN'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'DAĞHAN'.
GS_DATA-SOYAD = 'BALTACI'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'BMUH'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'İDRİS'.
GS_DATA-SOYAD = 'BUGRA'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'TOGR'.
APPEND GS_DATA TO GT_DATAS.

CLEAR GS_DATA.
GS_DATA-AD = 'DURAN'.
GS_DATA-SOYAD = 'ÖZKÖKER'.
GS_DATA-CINSIYET = 'E'.
GS_DATA-BOLUM = 'KOGR'.
APPEND GS_DATA TO GT_DATAS.


"$. Endregion Tablo Doldurma

DESCRIBE TABLE GT_DATAS LINES GV_SAYI.

DO GV_SAYI TIMES.
  READ TABLE GT_DATAS INDEX SY-INDEX INTO GS_DATA.
  GS_DATA-HARC = '800'.
  MODIFY GT_DATAS FROM GS_DATA INDEX sy-INDEX.
ENDDO.


WRITE /'Program sonu'.
